-- Curated starter catalog: 50 standard pickleball shots, 50 drills, and their relationships.
-- Situation ranges are Repertoire heuristics for discovery, not official rules or coaching prescriptions.

insert into public.shots (
  name, court_x_min, court_x_max, court_y_min, court_y_max,
  ball_height_min, ball_height_max, intent_min, intent_max,
  difficulty, description, instructions
)
values
  ('Flat Serve', -15, 15, 0, 2, 1, 3, 55, 85, 1, 'A firm, low-trajectory serve aimed deep to start the point.', 'Contact in front, keep the motion smooth, and recover toward the center.'),
  ('Topspin Serve', -15, 15, 0, 5, 1, 4, 60, 90, 2, 'A dipping serve that uses topspin to pressure the returner.', 'Brush up the back of the ball and send it deep with margin over the net.'),
  ('Slice Serve', -15, 15, 0, 5, 1, 4, 45, 80, 2, 'A serve with side and underspin that changes the bounce and angle.', 'Carve across the ball while prioritizing depth and a legal contact point.'),
  ('High Deep Serve', -15, 15, 0, 4, 1, 5, 35, 70, 1, 'A high-margin serve that pushes the returner well behind the baseline.', 'Use a taller arc and aim through the back third of the service box.'),
  ('Short Angle Serve', -15, 15, 0, 7, 1, 4, 40, 75, 3, 'A shorter angled serve that pulls the returner away from the middle.', 'Use touch and angle without leaving the ball high or attackable.'),
  ('Deep Forehand Return', -15, 15, 0, 8, 2, 6, 45, 80, 1, 'A deep return that buys time and keeps the serving team back.', 'Strike out in front and send the ball high over the net toward the baseline.'),
  ('Deep Backhand Return', -15, 15, 0, 8, 2, 6, 45, 80, 2, 'A controlled backhand return that makes the third shot difficult.', 'Turn the shoulders early and finish high toward the deep middle.'),
  ('Crosscourt Return', -15, 15, 0, 10, 2, 7, 45, 85, 2, 'A diagonal return that creates space and a longer path to the kitchen.', 'Use the crosscourt angle to create depth while recovering forward.'),
  ('Soft Return', -15, 15, 0, 9, 2, 6, 25, 60, 2, 'A softer return designed to reduce the serving team''s attacking options.', 'Absorb pace with a stable paddle face and land the ball deep enough to be safe.'),
  ('Return Drop', -15, 15, 0, 12, 3, 7, 35, 70, 3, 'A return that arcs softly into the kitchen to begin a controlled transition.', 'Use a compact swing and let the ball travel through the target window.'),
  ('Chip Return', -15, 15, 0, 9, 2, 5, 35, 70, 2, 'A low skidding return that keeps the receiver uncomfortable.', 'Keep the paddle face slightly open and drive through the back of the ball.'),
  ('Third Shot Drop', -12, 4, 15, 30, 4, 8, 45, 75, 3, 'A soft third shot that lands in the kitchen and lets the team advance.', 'Use a relaxed arc, clear the net by a safe margin, and move behind the ball.'),
  ('Third Shot Drop Backhand', -12, 2, 15, 30, 4, 8, 45, 75, 3, 'A backhand drop used to neutralize the transition from deep court.', 'Set the paddle early and guide the ball with a quiet shoulder turn.'),
  ('Third Shot Drive', -12, 12, 15, 30, 2, 6, 65, 95, 2, 'A firm third-shot drive that challenges an opponent before the drop.', 'Drive through the ball at the feet, then be ready for the next ball.'),
  ('Third Shot Drive Down the Line', -12, 0, 15, 30, 2, 6, 70, 98, 3, 'A line drive that attacks the outside shoulder and opens the court.', 'Choose it when the line is clear and recover quickly toward the middle.'),
  ('Third Shot Drive Crosscourt', 0, 12, 15, 30, 2, 6, 65, 95, 3, 'A crosscourt drive that creates a difficult angle during transition.', 'Keep the ball low and target the opponent''s outside foot.'),
  ('Hybrid Third Shot', -12, 12, 15, 30, 3, 7, 50, 85, 4, 'A disguised third shot that can become either a drive or a drop.', 'Use the same preparation for both choices and decide late from the ball.'),
  ('Forehand Crosscourt Dink', -15, 15, 0, 15, 1, 4, 25, 65, 1, 'A patient diagonal dink that moves an opponent without over-pressuring.', 'Brush under the ball with a soft grip and clear the net by inches.'),
  ('Backhand Crosscourt Dink', -15, 15, 0, 15, 1, 4, 25, 65, 2, 'A reliable backhand dink for sustaining a diagonal exchange.', 'Keep the backswing small and lift from the shoulder with a relaxed hand.'),
  ('Straight Ahead Dink', -8, 8, 0, 15, 1, 4, 20, 60, 1, 'A straight dink that holds the middle and tests paddle discipline.', 'Aim at the opponent''s inside foot and avoid giving the ball extra height.'),
  ('Forehand Roll Dink', -10, 10, 0, 15, 2, 5, 45, 80, 3, 'A topspin dink that rises over the net and drops at the opponent''s feet.', 'Accelerate gradually from low to high while keeping the ball on a safe arc.'),
  ('Backhand Roll Dink', -10, 10, 0, 15, 2, 5, 45, 80, 3, 'A backhand topspin roll that turns a neutral dink into controlled pressure.', 'Start below the ball and brush up without opening the paddle face.'),
  ('Dink to the Body', -8, 8, 0, 15, 1, 4, 30, 70, 2, 'A dink directed at the opponent''s hip to create a difficult decision.', 'Use a compact stroke and target the space between the opponent''s feet.'),
  ('Dink Reset', -15, 15, 0, 18, 2, 6, 15, 55, 2, 'A soft defensive dink used to lower the pace and regain neutral control.', 'Take pace off the ball and prioritize height, depth, and recovery.'),
  ('Forehand Speed-Up', -10, 10, 0, 15, 2, 5, 70, 100, 3, 'An upward attack from the kitchen that accelerates a dink exchange.', 'Attack a ball above net height and finish through the target.'),
  ('Backhand Speed-Up', -10, 10, 0, 15, 2, 5, 70, 100, 4, 'A compact backhand acceleration that targets the body or shoulder.', 'Load the legs, keep the swing short, and recover for the counter.'),
  ('Body Speed-Up', -8, 8, 0, 15, 2, 5, 65, 95, 3, 'A kitchen attack aimed at the opponent''s torso and paddle-side hip.', 'Choose a ball above the net and attack into the reaction window.'),
  ('Forehand Punch Volley', -15, 15, 0, 22, 3, 8, 55, 90, 2, 'A firm volley that redirects pace while holding the kitchen line.', 'Use a short punch with the paddle in front and no large backswing.'),
  ('Backhand Punch Volley', -15, 15, 0, 22, 3, 8, 50, 88, 2, 'A compact backhand volley for blocking or redirecting a fast ball.', 'Keep the wrist firm, absorb pace, and aim through the open court.'),
  ('Forehand Block Volley', -15, 15, 0, 25, 3, 9, 20, 65, 1, 'A soft blocking volley that neutralizes an incoming attack.', 'Present the paddle early and let the opponent''s pace do the work.'),
  ('Backhand Block Volley', -15, 15, 0, 25, 3, 9, 20, 65, 2, 'A backhand reset volley that keeps a fast exchange under control.', 'Cushion the ball with a stable face and keep the target low.'),
  ('Forehand Roll Volley', -12, 15, 0, 22, 3, 7, 55, 92, 3, 'A topspin volley that dips sharply into an opponent''s feet.', 'Start low, accelerate upward, and finish compactly over the net.'),
  ('Backhand Roll Volley', -15, 12, 0, 22, 3, 7, 55, 92, 4, 'A backhand roll volley used to turn a reachable ball into pressure.', 'Brush up the back of the ball while maintaining balance at the line.'),
  ('Forehand Reset', -12, 12, 10, 25, 3, 8, 15, 55, 2, 'A soft forehand transition shot that brings a fast rally back to neutral.', 'Absorb the ball in front and arc it toward the kitchen.'),
  ('Backhand Reset', -12, 12, 10, 25, 3, 8, 15, 55, 2, 'A backhand transition reset that takes speed out of an attack.', 'Keep the paddle face stable and lift the ball with your legs.'),
  ('Forehand Drive at the Feet', -12, 12, 12, 30, 2, 6, 60, 95, 2, 'A transition drive aimed low at the opponent''s shoes.', 'Drive through the target and expect a block or counter in return.'),
  ('Backhand Drive at the Feet', -12, 12, 12, 30, 2, 6, 60, 95, 3, 'A backhand transition drive that keeps the ball below volley height.', 'Turn early, contact in front, and recover immediately after the swing.'),
  ('Defensive Forehand Lob', -15, 15, 0, 15, 2, 7, 20, 60, 2, 'A high defensive lob that buys time when pinned in the kitchen.', 'Lift from underneath the ball and favor height over a risky line.'),
  ('Defensive Backhand Lob', -15, 15, 0, 15, 2, 7, 20, 60, 3, 'A backhand lob used to escape pressure and reset court position.', 'Open the face, extend upward, and send the ball deep over the opponent.'),
  ('Offensive Lob', -15, 15, 0, 15, 2, 6, 55, 88, 3, 'A disguised lob that sends a kitchen opponent moving backward.', 'Use a dink-like preparation and lift over the non-volley line player.'),
  ('Forehand Overhead', -15, 15, 0, 30, 6, 10, 75, 100, 2, 'A controlled overhead used to finish a high ball.', 'Move behind the ball, contact at full reach, and recover after the swing.'),
  ('Backhand Overhead', -15, 15, 0, 30, 6, 10, 65, 98, 4, 'A backhand-side overhead for balls that cannot be taken with the forehand.', 'Turn early, use the non-paddle arm for balance, and prioritize placement.'),
  ('Overhead to the Middle', -15, 15, 0, 30, 6, 10, 70, 100, 2, 'A high-percentage overhead aimed at the middle seam.', 'Choose depth and body safety over maximum pace.'),
  ('Erne', -15, 15, 0, 15, 2, 7, 75, 100, 5, 'An advanced airborne attack around the kitchen corner.', 'Recognize the setup early, clear the non-volley zone legally, and land balanced.'),
  ('ATP Attempt', -15, 15, 0, 15, 1, 6, 70, 100, 5, 'An around-the-post attack used when the ball travels wide beyond the post.', 'Wait for a legal angle and keep the swing controlled through the opening.'),
  ('Poach Volley', -8, 8, 0, 22, 3, 8, 60, 95, 3, 'A partner-positioning volley that takes a ball from the middle.', 'Communicate first, cross decisively, and punch into the open court.'),
  ('Scorpion Defense', -12, 12, 0, 18, 4, 9, 35, 80, 5, 'An emergency behind-the-body defense for a dipping lob or fast ball.', 'Stay athletic, keep the paddle head high, and prioritize simply getting it back.'),
  ('Drop Volley', -12, 12, 0, 22, 2, 6, 35, 75, 3, 'A soft volley that lands short when a hard attack is not available.', 'Cushion the ball with a slightly open face and hold your kitchen position.'),
  ('Bert', -8, 8, 0, 18, 2, 7, 65, 98, 5, 'An advanced partner play where one player crosses to attack a middle ball.', 'Coordinate the crossover, protect the middle, and attack only with a clear lane.'),
  ('Third Shot Drop from the Middle', -5, 5, 15, 30, 4, 8, 45, 75, 3, 'A central drop that uses the safest net path during transition.', 'Aim through the middle window and communicate who owns the next ball.'),
  ('Kitchen Line Dink Exchange', -8, 8, 0, 12, 1, 4, 20, 60, 1, 'A neutral kitchen shot used to sustain a patient exchange.', 'Keep the ball low, move your feet, and wait for a clear attackable ball.');

insert into public.drills (name, description)
values
  ('Serve Deep and Recover', 'Hit deep serves to both targets, recover to position, and track the return.'),
  ('Topspin Serve Targets', 'Alternate wide and body topspin serves while maintaining legal contact.'),
  ('Return Three Depths', 'Practice short, medium, and deep returns with a consistent recovery step.'),
  ('Return Drop Progression', 'Start with controlled returns and gradually add a soft drop option.'),
  ('Third Shot Drop Ladder', 'Hit drops to three kitchen targets and move forward behind each ball.'),
  ('Third Shot Drive at Feet', 'Drive alternating forehand and backhand balls at a moving blocker.'),
  ('Drop or Drive Read', 'Choose a drop or drive based on height, depth, and opponent position.'),
  ('Crosscourt Dink Cooperative', 'Sustain a diagonal dink rally while maintaining height and shape.'),
  ('Dink to the Body', 'Alternate crosscourt dinks with controlled body targets.'),
  ('Roll Dink Build-Up', 'Start with neutral dinks and add topspin rolls only on attackable balls.'),
  ('Dink Reset Challenge', 'Recover from high or wide dinks by returning the exchange to neutral.'),
  ('Kitchen Speed-Up Read', 'Attack selected balls and defend the counter without leaving the line.'),
  ('Body Speed-Up Pattern', 'Practice body attacks followed by a prepared counter volley.'),
  ('Punch Volley Directionals', 'Redirect feeds to middle, sideline, and opponent''s feet.'),
  ('Block Volley Absorption', 'Take pace off fast feeds and land resets into the kitchen.'),
  ('Roll Volley Progression', 'Build from stationary roll volleys into live transition movement.'),
  ('Transition Reset Corridor', 'Move through the transition zone while resetting balls below net height.'),
  ('Forehand Backhand Reset', 'Alternate sides and recover to the center after each soft reset.'),
  ('Feet Drive and Follow', 'Drive low at the feet, advance, and prepare for the next block.'),
  ('Defensive Lob Escape', 'Use high lobs to escape kitchen pressure and recover court position.'),
  ('Offensive Lob Disguise', 'Mix dinks and lobs from the same preparation to test depth control.'),
  ('Overhead Placement Grid', 'Place overheads deep, to the middle seam, and away from the defender.'),
  ('Overhead Recovery', 'Move back, set the feet, hit the overhead, and recover for the next ball.'),
  ('Erne Recognition', 'Practice recognizing wide balls before attempting a controlled airborne attack.'),
  ('ATP Angle Builder', 'Develop around-the-post angles from progressively wider feeds.'),
  ('Poach Communication', 'Call the poach, cross decisively, and finish with a compact volley.'),
  ('Scorpion Emergency Defense', 'React to high dipping balls with balanced emergency defense.'),
  ('Drop Volley Touch', 'Take a high transition ball softly and land it short.'),
  ('Bert Coordination', 'Rehearse the crossover pattern and protect the partner''s exposed space.'),
  ('Middle Ball Decisions', 'Resolve shared middle balls with clear communication and priority rules.'),
  ('Serve Return Third Ball', 'Play a complete serve, return, and third-shot sequence.'),
  ('Drive Drop Combo', 'Alternate a firm drive with a soft drop to change rally rhythm.'),
  ('Dink Speed-Up Counter', 'Dink patiently, speed up selectively, and defend the counter.'),
  ('Kitchen Line Patience', 'Score only after creating a clear opening during a dink exchange.'),
  ('Reset to Advance', 'Reset from transition, move forward, then establish kitchen position.'),
  ('Deep Middle Pressure', 'Use deep middle shots to create communication pressure.'),
  ('Wide Ball Recovery', 'Recover after wide shots and return to a balanced court position.'),
  ('Backhand Stability', 'Build reliable backhand drops, dinks, resets, and volleys.'),
  ('Forehand Attack Series', 'Sequence drives, speed-ups, and roll volleys from forehand contact.'),
  ('Two-Bounce Transition', 'Respect the bounce while progressing from baseline to kitchen.'),
  ('Target Three Zones', 'Rotate through crosscourt, middle, and line targets with control.'),
  ('Pressure Point Reps', 'Repeat a shot pattern while adding score and consequence pressure.'),
  ('Live Kitchen Rally', 'Play out kitchen points with restrictions on attack selection.'),
  ('Live Transition Rally', 'Start deep and earn the kitchen through drops, drives, and resets.'),
  ('Partner Movement Mirror', 'Match partner movement while keeping paddle position ready.'),
  ('Random Feed Recognition', 'Identify the correct shot from randomized height and court position.'),
  ('Shot Selection Circuit', 'Rotate through serve, return, drop, dink, attack, and defense stations.'),
  ('Consistency to Pressure', 'Build a repeatable stroke first, then add pace and placement.'),
  ('End-of-Rally Finish', 'Create a high ball and finish with the safest available attack.'),
  ('Repertoire Review Circuit', 'Cycle through foundational shots and record confidence after each set.');

insert into public.shot_drills (shot_id, drill_id)
select shots.id, drills.id
from (values
  ('Flat Serve', 'Serve Deep and Recover'),
  ('Topspin Serve', 'Topspin Serve Targets'),
  ('Slice Serve', 'Serve Deep and Recover'),
  ('High Deep Serve', 'Serve Deep and Recover'),
  ('Short Angle Serve', 'Topspin Serve Targets'),
  ('Deep Forehand Return', 'Return Three Depths'),
  ('Deep Backhand Return', 'Return Three Depths'),
  ('Crosscourt Return', 'Return Three Depths'),
  ('Soft Return', 'Return Drop Progression'),
  ('Return Drop', 'Return Drop Progression'),
  ('Chip Return', 'Return Three Depths'),
  ('Third Shot Drop', 'Third Shot Drop Ladder'),
  ('Third Shot Drop Backhand', 'Third Shot Drop Ladder'),
  ('Third Shot Drive', 'Third Shot Drive at Feet'),
  ('Third Shot Drive Down the Line', 'Third Shot Drive at Feet'),
  ('Third Shot Drive Crosscourt', 'Third Shot Drive at Feet'),
  ('Hybrid Third Shot', 'Drop or Drive Read'),
  ('Forehand Crosscourt Dink', 'Crosscourt Dink Cooperative'),
  ('Backhand Crosscourt Dink', 'Crosscourt Dink Cooperative'),
  ('Straight Ahead Dink', 'Kitchen Line Patience'),
  ('Forehand Roll Dink', 'Roll Dink Build-Up'),
  ('Backhand Roll Dink', 'Roll Dink Build-Up'),
  ('Dink to the Body', 'Dink to the Body'),
  ('Dink Reset', 'Dink Reset Challenge'),
  ('Forehand Speed-Up', 'Kitchen Speed-Up Read'),
  ('Backhand Speed-Up', 'Kitchen Speed-Up Read'),
  ('Body Speed-Up', 'Body Speed-Up Pattern'),
  ('Forehand Punch Volley', 'Punch Volley Directionals'),
  ('Backhand Punch Volley', 'Punch Volley Directionals'),
  ('Forehand Block Volley', 'Block Volley Absorption'),
  ('Backhand Block Volley', 'Block Volley Absorption'),
  ('Forehand Roll Volley', 'Roll Volley Progression'),
  ('Backhand Roll Volley', 'Roll Volley Progression'),
  ('Forehand Reset', 'Transition Reset Corridor'),
  ('Backhand Reset', 'Forehand Backhand Reset'),
  ('Forehand Drive at the Feet', 'Feet Drive and Follow'),
  ('Backhand Drive at the Feet', 'Feet Drive and Follow'),
  ('Defensive Forehand Lob', 'Defensive Lob Escape'),
  ('Defensive Backhand Lob', 'Defensive Lob Escape'),
  ('Offensive Lob', 'Offensive Lob Disguise'),
  ('Forehand Overhead', 'Overhead Placement Grid'),
  ('Backhand Overhead', 'Overhead Recovery'),
  ('Overhead to the Middle', 'Overhead Placement Grid'),
  ('Erne', 'Erne Recognition'),
  ('ATP Attempt', 'ATP Angle Builder'),
  ('Poach Volley', 'Poach Communication'),
  ('Scorpion Defense', 'Scorpion Emergency Defense'),
  ('Drop Volley', 'Drop Volley Touch'),
  ('Bert', 'Bert Coordination'),
  ('Third Shot Drop from the Middle', 'Middle Ball Decisions'),
  ('Kitchen Line Dink Exchange', 'Kitchen Line Patience')
) as mapping(shot_name, drill_name)
join public.shots on shots.name = mapping.shot_name
join public.drills on drills.name = mapping.drill_name
on conflict do nothing;
